# Generated by Django 4.1.3 on 2022-11-29 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, help_text='user phone number', max_length=255, null=True)),
                ('dob', models.DateField(blank=True, help_text='user date of birth', null=True)),
                ('city', models.CharField(blank=True, help_text="user's city ", max_length=255, null=True)),
                ('lang', models.CharField(choices=[('EN', 'EN'), ('FR', 'FR')], default='EN', help_text='user language', max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
