# Generated by Django 4.1.3 on 2022-11-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_city_alter_profile_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lang',
            field=models.CharField(choices=[('EN', 'EN'), ('FR', 'FR')], default='EN', max_length=2),
        ),
    ]
