# Generated by Django 4.1.3 on 2022-11-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lang',
            field=models.CharField(choices=[('EN', 'EN'), ('FR', 'FR')], default='EN', help_text='user language', max_length=2),
        ),
    ]
