
EAS = eas
NPM = npm

install:
	$(NPM) install -g eas-cli

login:
	$(EAS) login

configure:
	$(EAS) build:configure

build-android:
	$(EAS) build --platform android

build-ios:
	$(EAS) build --platform ios


# Equivilent class partition : test within a specific range
# Structural ans dynamic : 2 example of your choice
# Control flow testing: -> path coverage,cyclomatic complexity
# Dataflow testing -> list all data flow techniques : all uses,all sum,all predicates
# Symbolic execution -> take any program of your choice :-> show all the symbolic tree and symbolic store
# metamorphic testing