# Generated by Django 4.1.3 on 2022-11-19 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('balance', models.BigIntegerField(default=0, help_text='User account balance')),
                ('account_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=255)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('pin_code', models.CharField(default='00000', help_text='pin code use to manage transaction in a user account', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_agent', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-balance'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.FloatField(help_text='charge in % example 0.2 ')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField()),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='core.account')),
                ('withdraw_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_from', to='core.transactioncharge')),
                ('withdraw_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_from', to='core.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField()),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_charge', to='core.transactioncharge')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='core.account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='core.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transactioncharge',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_type', to='core.transactiontype'),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField()),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('deposit_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_from', to='core.account')),
                ('deposit_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_to', to='core.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
