# Generated by Django 4.1.3 on 2022-11-27 05:52

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('balance', models.BigIntegerField(default=0, help_text='User account balance')),
                ('account_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=255)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('AED', 'AED'), ('AFN', 'AFN'), ('ALL', 'ALL'), ('AMD', 'AMD'), ('ANG', 'ANG'), ('AOA', 'AOA'), ('ARS', 'ARS'), ('AUD', 'AUD'), ('AWG', 'AWG'), ('AZN', 'AZN'), ('BAM', 'BAM'), ('BBD', 'BBD'), ('BDT', 'BDT'), ('BGN', 'BGN'), ('BHD', 'BHD'), ('BIF', 'BIF'), ('BMD', 'BMD'), ('BND', 'BND'), ('BOB', 'BOB'), ('BRL', 'BRL'), ('BSD', 'BSD'), ('BTN', 'BTN'), ('BWP', 'BWP'), ('BYN', 'BYN'), ('BZD', 'BZD'), ('CAD', 'CAD'), ('CDF', 'CDF'), ('CHF', 'CHF'), ('CLP', 'CLP'), ('CNY', 'CNY'), ('COP', 'COP'), ('CRC', 'CRC'), ('CUP', 'CUP'), ('CVE', 'CVE'), ('CZK', 'CZK'), ('DJF', 'DJF'), ('DKK', 'DKK'), ('DOP', 'DOP'), ('DZD', 'DZD'), ('EGP', 'EGP'), ('ERN', 'ERN'), ('ETB', 'ETB'), ('EUR', 'EUR'), ('FJD', 'FJD'), ('FKP', 'FKP'), ('FOK', 'FOK'), ('GBP', 'GBP'), ('GEL', 'GEL'), ('GGP', 'GGP'), ('GHS', 'GHS'), ('GIP', 'GIP'), ('GMD', 'GMD'), ('GNF', 'GNF'), ('GTQ', 'GTQ'), ('GYD', 'GYD'), ('HKD', 'HKD'), ('HNL', 'HNL'), ('HRK', 'HRK'), ('HTG', 'HTG'), ('HUF', 'HUF'), ('IDR', 'IDR'), ('ILS', 'ILS'), ('IMP', 'IMP'), ('INR', 'INR'), ('IQD', 'IQD'), ('IRR', 'IRR'), ('ISK', 'ISK'), ('JEP', 'JEP'), ('JMD', 'JMD'), ('JOD', 'JOD'), ('JPY', 'JPY'), ('KES', 'KES'), ('KGS', 'KGS'), ('KHR', 'KHR'), ('KID', 'KID'), ('KMF', 'KMF'), ('KRW', 'KRW'), ('KWD', 'KWD'), ('KYD', 'KYD'), ('KZT', 'KZT'), ('LAK', 'LAK'), ('LBP', 'LBP'), ('LKR', 'LKR'), ('LRD', 'LRD'), ('LSL', 'LSL'), ('LYD', 'LYD'), ('MAD', 'MAD'), ('MDL', 'MDL'), ('MGA', 'MGA'), ('MKD', 'MKD'), ('MMK', 'MMK'), ('MNT', 'MNT'), ('MOP', 'MOP'), ('MRU', 'MRU'), ('MUR', 'MUR'), ('MVR', 'MVR'), ('MWK', 'MWK'), ('MXN', 'MXN'), ('MYR', 'MYR'), ('MZN', 'MZN'), ('NAD', 'NAD'), ('NGN', 'NGN'), ('NIO', 'NIO'), ('NOK', 'NOK'), ('NPR', 'NPR'), ('NZD', 'NZD'), ('OMR', 'OMR'), ('PAB', 'PAB'), ('PEN', 'PEN'), ('PGK', 'PGK'), ('PHP', 'PHP'), ('PKR', 'PKR'), ('PLN', 'PLN'), ('PYG', 'PYG'), ('QAR', 'QAR'), ('RON', 'RON'), ('RSD', 'RSD'), ('RUB', 'RUB'), ('RWF', 'RWF'), ('SAR', 'SAR'), ('SBD', 'SBD'), ('SCR', 'SCR'), ('SDG', 'SDG'), ('SEK', 'SEK'), ('SGD', 'SGD'), ('SHP', 'SHP'), ('SLE', 'SLE'), ('SLL', 'SLL'), ('SOS', 'SOS'), ('SRD', 'SRD'), ('SSP', 'SSP'), ('STN', 'STN'), ('SYP', 'SYP'), ('SZL', 'SZL'), ('THB', 'THB'), ('TJS', 'TJS'), ('TMT', 'TMT'), ('TND', 'TND'), ('TOP', 'TOP'), ('TRY', 'TRY'), ('TTD', 'TTD'), ('TVD', 'TVD'), ('TWD', 'TWD'), ('TZS', 'TZS'), ('UAH', 'UAH'), ('UGX', 'UGX'), ('UYU', 'UYU'), ('UZS', 'UZS'), ('VES', 'VES'), ('VND', 'VND'), ('VUV', 'VUV'), ('WST', 'WST'), ('XAF', 'XAF'), ('XCD', 'XCD'), ('XDR', 'XDR'), ('XOF', 'XOF'), ('XPF', 'XPF'), ('YER', 'YER'), ('ZAR', 'ZAR'), ('ZMW', 'ZMW'), ('ZWL', 'ZWL')], default='XAF', help_text='currency', max_length=3)),
                ('pin_code', models.CharField(default='00000', help_text='pin code use to manage transaction in a user account', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_agent', models.BooleanField(default=False, help_text='determines wether an account is a simple account or an agent account')),
                ('user', models.OneToOneField(help_text='user id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.FloatField(default=0, help_text='charge in % example 0.2 ')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DEPOSIT', 'DESPOSIT'), ('TRANSFER', 'TRANSFER'), ('WITHDRAW', 'WITHDRAW')], help_text='transaction type name', max_length=25, unique=True)),
                ('description', models.CharField(help_text='transaction type description', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.FloatField(help_text='the transaction amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='time at which the transaction was created')),
                ('agent', models.ForeignKey(help_text='the account id of the user from which the money is withdraw from', on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='core.account')),
                ('withdraw_charge', models.ForeignKey(blank=True, help_text='the transaction charge id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_charge', to='core.transactioncharge')),
                ('withdraw_from', models.ForeignKey(help_text='the account id of the agent making the transaction', on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_from', to='core.account', validators=[core.validators.IsAgent])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.FloatField(help_text='the transaction amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='time at which the transaction was created')),
                ('charge', models.ForeignKey(help_text='the transaction type id', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_charge', to='core.transactioncharge')),
                ('reciever', models.ForeignKey(help_text='the reciever account id', on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='core.account')),
                ('sender', models.ForeignKey(help_text='the account sender id', on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='core.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transactioncharge',
            name='type',
            field=models.OneToOneField(help_text='transaction type id', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_type', to='core.transactiontype'),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.FloatField(help_text='the transaction amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='time at which the transaction was created')),
                ('deposit_from', models.ForeignKey(help_text='the account id which is depositing the money', on_delete=django.db.models.deletion.CASCADE, related_name='deposit_from', to='core.account', validators=[core.validators.IsAgent])),
                ('deposit_to', models.ForeignKey(help_text='the account id which is recieving the money', on_delete=django.db.models.deletion.CASCADE, related_name='deposit_to', to='core.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
