# Generated by Django 4.1.3 on 2022-11-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(choices=[('DEPOSIT', 'WITHDRAW'), ('TRANSFER', 'TRANSFER'), ('WITHDRAW', 'WITHDRAW')], max_length=25, unique=True),
        ),
    ]
