# Generated by Django 4.1.3 on 2022-11-26 22:49

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_account_currency_alter_account_is_agent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='deposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='time at which the transaction was created'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposit_from',
            field=models.ForeignKey(help_text='the account id which is depositing the money', on_delete=django.db.models.deletion.CASCADE, related_name='deposit_from', to='core.account', validators=[core.validators.IsAgent]),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='time at which the transaction was created'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='time at which the transaction was created'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='withdraw_from',
            field=models.ForeignKey(help_text='the account id of the agent making the transaction', on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_from', to='core.account', validators=[core.validators.IsAgent]),
        ),
    ]
