# Generated by Django 4.1.3 on 2022-11-26 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_account_options_alter_deposit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='withdraw_charge',
            field=models.ForeignKey(blank=True, help_text='the transaction charge id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_charge', to='core.transactioncharge'),
        ),
    ]
